apiVersion: v1
kind: Service
metadata:
  name: NAME-service
  namespace: NAME
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3080
      protocol: TCP
      name: http
  # pods selector for routing traffic
  selector:
    app: NAME-app
